# Generated by Django 2.2.1 on 2019-06-18 05:20

import db.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subcategory',
            field=djongo.models.fields.ArrayModelField(default=[], model_container=db.models.SubCategory),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
