# Generated by Django 2.2.1 on 2019-07-06 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_tweetsearch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TweetSearch',
        ),
    ]
